[package]
name = "vba-utils"
version = "0.1.0"
edition = "2024"

[dependencies]
tree-sitter = "0.20"
chrono = { version = "0.4", features = ["serde"] } 
anyhow = "1.0"
vba-parser = { path = "../vba-parser" }
