[package]
name = "vba-client"
version = "0.1.0"
edition = "2024"

[dependencies]
tree-sitter = "0.20.10"

# Local path to your tree-sitter grammar
vba-utils = { path = "../vba-utils" }
vba-parser = { path = "../vba-parser" }

[profile.release]
lto = true
codegen-units = 1
strip = true
opt-level = 3